version: '3.9'

name: "NewsPortal"

services:
  user-service:
    container_name: "user_service"
    build:
      context: ../Backend/
      dockerfile: ./UserService/Dockerfile
    ports:
      - "5229:5229"
    links:
      - user-service-postgreSQL
      - user-service-Redis
    depends_on:
      - user-service-postgreSQL
      - user-service-Redis
    environment:
      - ASPNETCORE_ENVIROMENT=Production
      - ASPNETCORE_URLS=http://+:5229
      - CONNECTION_STRING_USER_SERVICE=Host=user-service-postgreSQL;Username=postgres;Password=23022005;Database=UsersDb;
      - CONNECTION_STRING_REDIS=user-service-redis:6379


  user-service-postgreSQL:
    container_name: "user-service-postgreSQL"
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=UsersDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=23022005
    volumes:
      - user-service-postgre-volume:/var/lib/postgresql/data

  user-service-Redis:
    container_name: "user-service-Redis"
    image: redis:7.4.1-alpine
    restart: always
    ports:
      - "6379:6379"
  
  nginx:
    container_name: "nginx"
    image: nginx:alpine
    restart: always
    ports:
      - "7788:7788"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service

volumes:
  user-service-postgre-volume:
    driver: local